name: Try and install latest python on a ubuntu container

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    
    services:
      ubuntussh:
        image: mailtopulkit/ubuntussh:root

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Testing ssh action
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ubuntussh
        username: root
        password: coolpassword
        port: 22
        script: |
            whoami
            pwd
            ls -al