name: Try and install latest python on a ubuntu container

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    

    steps:
    - name: Check out code
      uses: actions/checkout@v3